[package]
name = "xcp"
description = "xcp is a (partial) clone of the Unix `cp` command with some more user-friendly feedback and some optimisations."
version = "0.6.3-alpha.0"
edition = "2018"

authors = ["Steve Smith <tarkasteve@gmail.com>"]
homepage = "https://github.com/tarka/xcp/"
repository = "https://github.com/tarka/xcp/"
readme = "README.md"

keywords = ["coreutils", "cp", "files", "filesystem"]
categories =["command-line-utilities"]
license = "GPL-3.0-only"

[badges]
circle-ci = { repository = "tarka/xcp" }
travis-ci = { repository = "tarka/xcp" }

[features]
default = ["kernel_copy_file_range"]
kernel_copy_file_range = []

[profile.release]
overflow-checks = true

[dependencies]
anyhow = "1.0.20"
cfg-if = "0.1.10"
clap = "2.33.0"
crossbeam-channel = "0.4.0"
crossbeam-utils = "0.7.0"
fiemap = "0.1.0"
glob = "0.3.0"
ignore = "0.4.10"
indicatif = "0.13.0"
libc = "0.2.65"
log = "0.4.8"
num_cpus = "1.11.1"
simplelog = "0.7.4"
structopt = "0.3.4"
thiserror = "1.0.5"
unbytify = "0.2.0"
walkdir = "2.2.9"

[dev-dependencies]
escargot = "0.5.0"
rand = "0.7.2"
rand_distr = "0.2.2"
rand_xorshift = "0.2.0"
tempfile = "3.1.0"
test-case = "0.3.3"
uuid = { version = "0.8.1", features = ["v4"] }
